
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: react
    kyma-grafana: enabled
  name: app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: react
        kyma-grafana: enabled
    spec:
      containers:
        - image: amirafathy/image4
          name: container4
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: react
                optional: true
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: react
  name: service4
spec:
  ports:
    - port: 3000
      name: http
      protocol: TCP
      targetPort: 3000
  selector:
    app: react
  type: ClusterIP
status:
  loadBalancer: {}


